// Category type definition
export type Category = {
  id: string;
  name: string;
  description: string;
  tags: string[];
};

// Categories array
export const categories: Category[] = [
  {
    id: "frontend",
    name: "Frontend Development",
    description: "React, Vue, Angular, and modern web technologies",
    tags: [
      "react",
      "vue",
      "angular",
      "nextjs",
      "nuxt",
      "typescript",
      "javascript",
      "css",
      "html",
      "tailwind",
      "svelte",
      "astro",
      "webpack",
      "vite",
      "styled-components",
      "sass",
      "less",
    ],
  },
  {
    id: "backend",
    name: "Backend Development",
    description: "Server-side programming and APIs",
    tags: [
      "node",
      "python",
      "java",
      "go",
      "rust",
      "php",
      "ruby",
      "express",
      "django",
      "fastapi",
      "spring",
      "gin",
      "laravel",
      "api",
      "rest",
      "graphql",
      "microservices",
      "serverless",
    ],
  },
  {
    id: "devops",
    name: "DevOps & Infrastructure",
    description: "Deployment, CI/CD, and cloud infrastructure",
    tags: [
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "terraform",
      "jenkins",
      "github-actions",
      "gitlab-ci",
      "ansible",
      "nginx",
      "linux",
      "bash",
      "monitoring",
      "logging",
      "security",
    ],
  },
  {
    id: "databases",
    name: "Databases & Data Engineering",
    description: "Database design, SQL, and data processing",
    tags: [
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "elasticsearch",
      "sql",
      "nosql",
      "data-engineering",
      "etl",
      "data-science",
      "big-data",
      "hadoop",
      "spark",
      "kafka",
      "airflow",
    ],
  },
  {
    id: "algorithms",
    name: "Data Structures & Algorithms",
    description: "Problem solving and algorithmic thinking",
    tags: [
      "algorithms",
      "data-structures",
      "leetcode",
      "competitive-programming",
      "dynamic-programming",
      "graph-algorithms",
      "sorting",
      "searching",
      "complexity",
      "optimization",
      "mathematics",
      "discrete-math",
    ],
  },
  {
    id: "mobile",
    name: "Mobile Development",
    description: "iOS, Android, and cross-platform development",
    tags: [
      "react-native",
      "flutter",
      "ios",
      "android",
      "swift",
      "kotlin",
      "mobile",
      "app-development",
      "xamarin",
      "ionic",
      "capacitor",
      "mobile-ui",
      "mobile-ux",
      "pwa",
      "hybrid-apps",
    ],
  },
  {
    id: "ai-ml",
    name: "AI & Machine Learning",
    description: "Artificial intelligence and data science",
    tags: [
      "ai",
      "machine-learning",
      "deep-learning",
      "tensorflow",
      "pytorch",
      "scikit-learn",
      "nlp",
      "computer-vision",
      "neural-networks",
      "data-science",
      "python",
      "jupyter",
      "pandas",
      "numpy",
    ],
  },
  {
    id: "career",
    name: "Career & Productivity",
    description: "Professional development and productivity tips",
    tags: [
      "career",
      "productivity",
      "soft-skills",
      "leadership",
      "mentoring",
      "interview",
      "resume",
      "networking",
      "remote-work",
      "time-management",
      "learning",
      "growth",
      "motivation",
      "work-life-balance",
    ],
  },
  {
    id: "webdev",
    name: "Web Development",
    description: "General web development topics",
    tags: [
      "webdev",
      "programming",
      "coding",
      "development",
      "software-engineering",
      "best-practices",
      "clean-code",
      "testing",
      "debugging",
      "performance",
      "accessibility",
      "seo",
      "web-standards",
      "browser-compatibility",
    ],
  },
];
