export interface RoutineItem {
  id: string;
  activityName: string;
  description: string;
  plannedDuration: number; // in minutes
  category?: string;
  timeBlock?: "morning" | "afternoon" | "evening";
  priority: number;
}

export interface Routine {
  id: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  isTemplate: boolean;
  isActive?: boolean;
  items: RoutineItem[];
}

export const dummyRoutines: Routine[] = [
  {
    id: "1",
    name: "Interview Preparation Day",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "1-1",
        activityName: "LeetCode Practice",
        description: "Focus on dynamic programming and graph problems",
        plannedDuration: 120,
        category: "Technical",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "1-2",
        activityName: "System Design Review",
        description: "Study distributed systems and scalability patterns",
        plannedDuration: 90,
        category: "Technical",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "1-3",
        activityName: "Behavioral Practice",
        description: "Prepare STAR method responses for common questions",
        plannedDuration: 60,
        category: "Soft Skills",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "2",
    name: "Work Focus Day",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "2-1",
        activityName: "Deep Work Session",
        description: "Focus on complex coding tasks without interruptions",
        plannedDuration: 180,
        category: "Work",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "2-2",
        activityName: "Team Collaboration",
        description: "Code reviews and pair programming sessions",
        plannedDuration: 120,
        category: "Work",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "2-3",
        activityName: "Documentation",
        description: "Update project documentation and write technical blogs",
        plannedDuration: 60,
        category: "Work",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "3",
    name: "My Current Routine",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    isActive: true,
    items: [
      {
        id: "3-1",
        activityName: "Interview Preparation",
        description: "Practice coding problems and system design",
        plannedDuration: 120,
        category: "Learning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "3-2",
        activityName: "Office Work",
        description: "Complete project tasks and attend meetings",
        plannedDuration: 360,
        category: "Work",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "3-3",
        activityName: "Leetcode Practice",
        description: "Solve medium to hard problems",
        plannedDuration: 120,
        category: "Learning",
        timeBlock: "evening",
        priority: 3,
      },
      {
        id: "3-4",
        activityName: "Job Search",
        description: "Update resume and apply to positions",
        plannedDuration: 60,
        category: "Career",
        timeBlock: "evening",
        priority: 4,
      },
    ],
  },
  {
    id: "4",
    name: "Weekend Learning",
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "4-1",
        activityName: "New Technology Study",
        description: "Learn about new frameworks and tools",
        plannedDuration: 180,
        category: "Learning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "4-2",
        activityName: "Project Work",
        description: "Work on personal projects",
        plannedDuration: 240,
        category: "Work",
        timeBlock: "afternoon",
        priority: 2,
      },
    ],
  },
  {
    id: "5",
    name: "Study Day",
    createdAt: new Date("2024-03-08"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "5-1",
        activityName: "Morning Study",
        description: "Focus on core concepts and theory",
        plannedDuration: 120,
        category: "Learning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "5-2",
        activityName: "Practice Session",
        description: "Apply learned concepts through exercises",
        plannedDuration: 180,
        category: "Learning",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "5-3",
        activityName: "Review & Notes",
        description: "Summarize key points and create study notes",
        plannedDuration: 60,
        category: "Learning",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "6",
    name: "Productivity Day",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "6-1",
        activityName: "Task Planning",
        description: "Organize and prioritize daily tasks",
        plannedDuration: 30,
        category: "Planning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "6-2",
        activityName: "Deep Work",
        description: "Focus on high-priority tasks",
        plannedDuration: 240,
        category: "Work",
        timeBlock: "morning",
        priority: 2,
      },
      {
        id: "6-3",
        activityName: "Review & Adjust",
        description: "Review progress and adjust plans",
        plannedDuration: 30,
        category: "Planning",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "7",
    name: "Weekend Routine",
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "7-1",
        activityName: "Morning Exercise",
        description: "Yoga and light workout",
        plannedDuration: 60,
        category: "Health",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "7-2",
        activityName: "Personal Projects",
        description: "Work on side projects and hobbies",
        plannedDuration: 240,
        category: "Personal",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "7-3",
        activityName: "Relaxation",
        description: "Reading and meditation",
        plannedDuration: 60,
        category: "Personal",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "8",
    name: "Freelance Day",
    createdAt: new Date("2024-03-14"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "8-1",
        activityName: "Client Work",
        description: "Focus on client projects",
        plannedDuration: 360,
        category: "Work",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "8-2",
        activityName: "Business Tasks",
        description: "Invoicing and admin work",
        plannedDuration: 120,
        category: "Work",
        timeBlock: "afternoon",
        priority: 2,
      },
    ],
  },
  {
    id: "9",
    name: "Health & Wellness Day",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "9-1",
        activityName: "Morning Workout",
        description: "Cardio and strength training",
        plannedDuration: 60,
        category: "Health",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "9-2",
        activityName: "Meal Prep",
        description: "Prepare healthy meals for the day",
        plannedDuration: 45,
        category: "Health",
        timeBlock: "morning",
        priority: 2,
      },
      {
        id: "9-3",
        activityName: "Meditation",
        description: "Mindfulness and breathing exercises",
        plannedDuration: 30,
        category: "Health",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "10",
    name: "Creative Day",
    createdAt: new Date("2024-03-11"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "10-1",
        activityName: "Brainstorming",
        description: "Generate new ideas and concepts",
        plannedDuration: 90,
        category: "Creative",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "10-2",
        activityName: "Prototyping",
        description: "Create quick prototypes and mockups",
        plannedDuration: 120,
        category: "Creative",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "10-3",
        activityName: "Feedback Session",
        description: "Review and refine creative work",
        plannedDuration: 60,
        category: "Creative",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "11",
    name: "Networking Day",
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "11-1",
        activityName: "LinkedIn Engagement",
        description: "Connect and engage with professionals",
        plannedDuration: 45,
        category: "Networking",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "11-2",
        activityName: "Virtual Meetups",
        description: "Attend online networking events",
        plannedDuration: 120,
        category: "Networking",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "11-3",
        activityName: "Follow-ups",
        description: "Send thank you notes and follow-ups",
        plannedDuration: 30,
        category: "Networking",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "12",
    name: "Research Day",
    createdAt: new Date("2024-03-13"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "12-1",
        activityName: "Literature Review",
        description: "Read and analyze research papers",
        plannedDuration: 120,
        category: "Research",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "12-2",
        activityName: "Data Analysis",
        description: "Process and analyze research data",
        plannedDuration: 180,
        category: "Research",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "12-3",
        activityName: "Report Writing",
        description: "Document findings and conclusions",
        plannedDuration: 90,
        category: "Research",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "13",
    name: "Language Learning Day",
    createdAt: new Date("2024-03-14"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: true,
    items: [
      {
        id: "13-1",
        activityName: "Vocabulary Practice",
        description: "Learn and review new words",
        plannedDuration: 45,
        category: "Learning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "13-2",
        activityName: "Grammar Study",
        description: "Study grammar rules and structures",
        plannedDuration: 60,
        category: "Learning",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "13-3",
        activityName: "Conversation Practice",
        description: "Practice speaking with native speakers",
        plannedDuration: 45,
        category: "Learning",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "14",
    name: "Content Creation Day",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "14-1",
        activityName: "Content Planning",
        description: "Plan blog posts and social media content",
        plannedDuration: 60,
        category: "Content",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "14-2",
        activityName: "Writing",
        description: "Create blog posts and articles",
        plannedDuration: 180,
        category: "Content",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "14-3",
        activityName: "Editing",
        description: "Review and edit content",
        plannedDuration: 60,
        category: "Content",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "15",
    name: "Project Management Day",
    createdAt: new Date("2024-03-16"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "15-1",
        activityName: "Project Review",
        description: "Review project status and milestones",
        plannedDuration: 90,
        category: "Management",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "15-2",
        activityName: "Team Meetings",
        description: "Conduct team syncs and one-on-ones",
        plannedDuration: 120,
        category: "Management",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "15-3",
        activityName: "Planning",
        description: "Plan next sprint and tasks",
        plannedDuration: 90,
        category: "Management",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "16",
    name: "Skill Development Day",
    createdAt: new Date("2024-03-17"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "16-1",
        activityName: "Online Courses",
        description: "Take online courses and tutorials",
        plannedDuration: 120,
        category: "Learning",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "16-2",
        activityName: "Practice Projects",
        description: "Work on skill-building projects",
        plannedDuration: 180,
        category: "Learning",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "16-3",
        activityName: "Review & Notes",
        description: "Review learning and take notes",
        plannedDuration: 60,
        category: "Learning",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "17",
    name: "Financial Planning Day",
    createdAt: new Date("2024-03-18"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "17-1",
        activityName: "Budget Review",
        description: "Review and update monthly budget",
        plannedDuration: 60,
        category: "Finance",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "17-2",
        activityName: "Investment Research",
        description: "Research investment opportunities",
        plannedDuration: 90,
        category: "Finance",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "17-3",
        activityName: "Financial Planning",
        description: "Plan long-term financial goals",
        plannedDuration: 60,
        category: "Finance",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
  {
    id: "18",
    name: "Personal Development Day",
    createdAt: new Date("2024-03-19"),
    updatedAt: new Date("2024-03-15"),
    isTemplate: false,
    items: [
      {
        id: "18-1",
        activityName: "Reading",
        description: "Read personal development books",
        plannedDuration: 60,
        category: "Personal",
        timeBlock: "morning",
        priority: 1,
      },
      {
        id: "18-2",
        activityName: "Journaling",
        description: "Reflect and write in journal",
        plannedDuration: 30,
        category: "Personal",
        timeBlock: "afternoon",
        priority: 2,
      },
      {
        id: "18-3",
        activityName: "Goal Setting",
        description: "Set and review personal goals",
        plannedDuration: 45,
        category: "Personal",
        timeBlock: "evening",
        priority: 3,
      },
    ],
  },
];
